[package]
name = "suites"
version = "0.1.0"
edition = "2021"
authors = [
  "Jeffrey McAteer <jeffrey-imabot@jmcateer.com>"
]



[dependencies]
port_scanner = "0.1"
qapi = { version = "0.14", features = [ "qmp", "qapi-qga" ] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

